"""first_revision

Revision ID: 15383e4a5064
Revises: 
Create Date: 2022-05-13 00:35:45.132513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15383e4a5064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eldorado_test',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('testfield', sa.String(), nullable=True),
    sa.Column('newtestfield', sa.Integer(), nullable=True),
    sa.Column('third_testfield', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eldorado_test_id'), 'eldorado_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eldorado_test_id'), table_name='eldorado_test')
    op.drop_table('eldorado_test')
    # ### end Alembic commands ###
