"""permissions

Revision ID: fdfadd943e28
Revises: 3990eef650cf
Create Date: 2022-05-28 22:39:21.550861

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fdfadd943e28"
down_revision = "3990eef650cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eldorado_permission",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eldorado_permission_id"), "eldorado_permission", ["id"], unique=False)
    op.create_table(
        "eldorado_role",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="role_permission_uc"),
    )
    op.create_index(op.f("ix_eldorado_role_id"), "eldorado_role", ["id"], unique=False)
    op.create_table(
        "eldorado_role_permission",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("role_id", sa.BIGINT(), nullable=False),
        sa.Column("permission_id", sa.BIGINT(), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["eldorado_permission.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["eldorado_role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="role_permission_uc"),
    )
    op.create_index(
        op.f("ix_eldorado_role_permission_id"), "eldorado_role_permission", ["id"], unique=False
    )
    op.create_table(
        "eldorado_user_permission",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("permission_id", sa.BIGINT(), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["eldorado_permission.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["eldorado_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "permission_id", name="role_permission_uc"),
    )
    op.create_index(
        op.f("ix_eldorado_user_permission_id"), "eldorado_user_permission", ["id"], unique=False
    )
    op.create_table(
        "eldorado_user_role",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("role_id", sa.BIGINT(), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["eldorado_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["eldorado_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="role_permission_uc"),
    )
    op.create_index(op.f("ix_eldorado_user_role_id"), "eldorado_user_role", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eldorado_user_role_id"), table_name="eldorado_user_role")
    op.drop_table("eldorado_user_role")
    op.drop_index(op.f("ix_eldorado_user_permission_id"), table_name="eldorado_user_permission")
    op.drop_table("eldorado_user_permission")
    op.drop_index(op.f("ix_eldorado_role_permission_id"), table_name="eldorado_role_permission")
    op.drop_table("eldorado_role_permission")

    op.drop_index(op.f("ix_eldorado_role_id"), table_name="eldorado_role")
    op.drop_table("eldorado_role")
    op.drop_index(op.f("ix_eldorado_permission_id"), table_name="eldorado_permission")
    op.drop_table("eldorado_permission")
    # ### end Alembic commands ###
