"""rev_0 first_revision

Revision ID: 3990eef650cf
Revises: 
Create Date: 2022-05-28 22:07:54.296494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3990eef650cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eldorado_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('join_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eldorado_user_id'), 'eldorado_user', ['id'], unique=False)
    op.create_table('eldorado_user_session',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['eldorado_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'last_activity', name='user_session_activity_uc')
    )
    op.create_index(op.f('ix_eldorado_user_session_id'), 'eldorado_user_session', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eldorado_user_session_id'), table_name='eldorado_user_session')
    op.drop_table('eldorado_user_session')
    op.drop_index(op.f('ix_eldorado_user_id'), table_name='eldorado_user')
    op.drop_table('eldorado_user')
    # ### end Alembic commands ###
