"""test 2

Revision ID: 3a04d63e8775
Revises: 99936ae550c0
Create Date: 2022-05-09 01:19:01.840590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a04d63e8775'
down_revision = '99936ae550c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eldorado_test', sa.Column('newtestfield', sa.Integer(), nullable=True))
    op.add_column('eldorado_test', sa.Column('third_testfield', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eldorado_test', 'third_testfield')
    op.drop_column('eldorado_test', 'newtestfield')
    # ### end Alembic commands ###
