"""rev_0 first_revision

Revision ID: 40641b8a9081
Revises: 
Create Date: 2022-05-16 00:15:28.491474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40641b8a9081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eldorado_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('join_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eldorado_user_id'), 'eldorado_user', ['id'], unique=False)
    op.create_table('eldorado_user_session',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['eldorado_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eldorado_user_session_id'), 'eldorado_user_session', ['id'], unique=False)
    op.drop_index('ix_eldorado_user_session_id', table_name='eldorado_user_session', schema='77530')
    op.drop_table('eldorado_user_session', schema='77530')
    op.drop_table('alembic_version', schema='77530')
    op.drop_index('ix_eldorado_user_id', table_name='eldorado_user', schema='77530')
    op.drop_table('eldorado_user', schema='77530')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eldorado_user',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"77530".eldorado_user_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('join_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='eldorado_user_pkey'),
    schema='77530',
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_eldorado_user_id', 'eldorado_user', ['id'], unique=False, schema='77530')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc'),
    schema='77530'
    )
    op.create_table('eldorado_user_session',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"77530".eldorado_user_session_id_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_activity', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('stale_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['77530.eldorado_user.id'], name='eldorado_user_session_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='eldorado_user_session_pkey'),
    schema='77530'
    )
    op.create_index('ix_eldorado_user_session_id', 'eldorado_user_session', ['id'], unique=False, schema='77530')
    op.drop_index(op.f('ix_eldorado_user_session_id'), table_name='eldorado_user_session')
    op.drop_table('eldorado_user_session')
    op.drop_index(op.f('ix_eldorado_user_id'), table_name='eldorado_user')
    op.drop_table('eldorado_user')
    # ### end Alembic commands ###
