"""test 1

Revision ID: 99936ae550c0
Revises: 
Create Date: 2022-05-09 01:17:57.227104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99936ae550c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eldorado_test',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('testfield', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eldorado_test_id'), 'eldorado_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eldorado_test_id'), table_name='eldorado_test')
    op.drop_table('eldorado_test')
    # ### end Alembic commands ###
