"""first migration test

Revision ID: bd376251ad2f
Revises: 
Create Date: 2022-04-28 00:21:58.738683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd376251ad2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eldorado_test',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('testfield', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eldorado_test_id'), 'eldorado_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eldorado_test_id'), table_name='eldorado_test')
    op.drop_table('eldorado_test')
    # ### end Alembic commands ###
